"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads backend/.env if present. Real credentials (DATABASE_URL, S3 keys,
# etc.) live there, never in this file - see .env.example for the template.
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 'django-insecure-_0@m3tl@8m3g)k-k+q!6+(7e=t+)e*mvubn7+*_-p%1%zs8fi_'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'storages',
    'accounts',
    'documents',
    'reviews',
    'audit',
    'backup',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Set DATABASE_URL (e.g. a Supabase Postgres connection string) in .env to
# use a cloud database. Falls back to local SQLite when it's not set, so the
# app keeps working before cloud credentials exist.

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# MEDIA_URL/MEDIA_ROOT are always defined (config/urls.py references them
# unconditionally to serve local media in DEBUG) even though they're only
# actually used for storage when the S3 backend below isn't active.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploaded document storage
# https://django-storages.readthedocs.io/
#
# Set AWS_STORAGE_BUCKET_NAME (+ the other AWS_* vars below) in .env to store
# uploaded files in S3-compatible cloud storage (e.g. Supabase Storage,
# Cloudflare R2, AWS S3 itself). Falls back to local disk under media/ when
# it's not set.

AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')

if AWS_STORAGE_BUCKET_NAME:
    STORAGES = {
        'default': {'BACKEND': 'storages.backends.s3.S3Storage'},
        'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
    }
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')  # unset for real AWS S3
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_ADDRESSING_STYLE = 'path'
    # Files are private by default; DocumentDownloadView fetches bytes
    # server-side with these credentials and streams them through the
    # existing permission check - nothing should ever rely on a public or
    # long-lived direct S3 URL bypassing that check.
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 300

# Backups (backup app). Writes into BACKUP_DIR and prunes down to
# BACKUP_RETENTION. Two ways to trigger a backup:
#  - `python manage.py run_backup`, invoked externally on a schedule by cron
#    / Windows Task Scheduler (see README).
#  - Automatically, from inside this process: if BACKUP_INTERVAL_SECONDS is
#    set (> 0), a background thread writes one every that many seconds for
#    as long as `manage.py runserver` is running. Set to 0 to disable - it
#    only fires while this process stays up, and a multi-worker production
#    server would run one independent timer per worker, so the run_backup
#    command is the more reliable choice outside a single dev server.
BACKUP_DIR = os.environ.get('BACKUP_DIR', str(BASE_DIR / 'backups'))
BACKUP_RETENTION = int(os.environ.get('BACKUP_RETENTION', '14'))
BACKUP_INTERVAL_SECONDS = int(os.environ.get('BACKUP_INTERVAL_SECONDS', '86400'))
# Where scheduled backups go: 'local' writes zips into BACKUP_DIR on this
# machine's disk; 'bucket' uploads them to the default file storage (the S3
# bucket when AWS_STORAGE_BUCKET_NAME is set) under BACKUP_S3_PREFIX, which
# survives redeploys on ephemeral-disk hosting. Manual downloads from the
# Backup page are unaffected - they always stream to the browser.
BACKUP_STORAGE = os.environ.get('BACKUP_STORAGE', 'local')
BACKUP_S3_PREFIX = os.environ.get('BACKUP_S3_PREFIX', 'backups/')

# Shared secret protecting /api/backup/cron/ (the scheduled-backup trigger
# for serverless hosting). Vercel Cron sends it as `Authorization: Bearer
# <CRON_SECRET>` automatically when a CRON_SECRET env var exists on the
# project. Unset (the default) = the endpoint 404s.
CRON_SECRET = os.environ.get('CRON_SECRET', '')

# --- Vercel serverless adjustments ---
# Vercel sets VERCEL=1 in its build and runtime environments. Serverless
# means: no long-lived process (so the in-process backup timer can never
# fire - Vercel Cron hits /api/backup/cron/ instead), and connections
# shouldn't be held open across invocations (conn_max_age=0; use Supabase's
# transaction pooler URL as DATABASE_URL, since the direct db.*.supabase.co
# host is IPv6-only and unreachable from Vercel functions).
if os.environ.get('VERCEL'):
    # Debug defaults ON for local dev but must never default on in a public
    # deployment - on Vercel it's opt-in via an explicit DEBUG=True env var.
    DEBUG = os.environ.get('DEBUG', 'False') == 'True'
    ALLOWED_HOSTS.append('.vercel.app')
    CSRF_TRUSTED_ORIGINS = ['https://*.vercel.app']
    BACKUP_INTERVAL_SECONDS = 0
    DATABASES['default'] = dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=0,
    )
    # Supabase's transaction pooler (the only Postgres route reachable from
    # Vercel) can't track Postgres server-side cursors across pooled
    # connections - Django queryset iteration then dies with
    # InvalidCursorName. Client-side cursors only.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
