# Generated by Django 6.0.7 on 2026-07-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='requires_acknowledgement',
        ),
        migrations.DeleteModel(
            name='DocumentAcknowledgement',
        ),
    ]
