# Generated by Django 6.0.7 on 2026-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_document_requires_acknowledgement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='normalized_title',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
