# Generated by Django 6.0.7 on 2026-07-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('edit_metadata', 'Edit metadata'), ('new_version', 'New version'), ('submit_for_review', 'Submit for review'), ('approve', 'Approve'), ('reject', 'Reject'), ('permission_grant', 'Permission grant'), ('permission_revoke', 'Permission revoke'), ('acknowledge', 'Acknowledge'), ('move', 'Move'), ('archive', 'Archive'), ('delete', 'Delete')], max_length=30)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
