# Generated by Django 6.0.7 on 2026-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'Upload'), ('view', 'View'), ('download', 'Download'), ('edit_metadata', 'Edit metadata'), ('new_version', 'New version'), ('submit_for_review', 'Submit for review'), ('approve', 'Approve'), ('reject', 'Reject'), ('permission_grant', 'Permission grant'), ('permission_revoke', 'Permission revoke'), ('acknowledge', 'Acknowledge'), ('move', 'Move'), ('delete', 'Delete')], max_length=30),
        ),
    ]
